export const THRESHOLD = 'THRESHOLD';
export const CURRENCY = 'CURRENCY';
export const SET_CURRENCY_DETAILS = 'SET_CURRENCY_DETAILS';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_VALIDATE_MESSAGE = 'SET_VALIDATE_MESSAGE';
export const RESET_VALIDATE_MESSAGE = 'RESET_VALIDATE_MESSAGE';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_USER = 'AUTH_USER';
