module.exports = {
    LOGOUT: 'Logout',
    LOGIN: 'Login',
    WELCOME: 'Welcome',
    TIME: 'Time (5m interval)',
    HIGH: 'High',
    LOW: 'Low',
    VOLUME: 'Volume',
    SELECT_CURRENCY: 'Select currency',
    ENTER_THRESHOLD: 'Enter Threshold',
    EMPTY_TABLE_MSG: 'No data available for given threshold',
    NO_THRESHOLD_MSG: 'Kindly enter threshold to view records.',
    LOGIN_FAILED_MSG: 'Sign in failed. Please check your username and password.',
    PAGE_NOT_FOUND_MSG: 'I\'m sorry, the page you were looking for cannot be found!',
    NOT_FOUND_CODE: '404 - Page Not Found',
    ENTER_DETAILS: 'Enter your details below.',
    EMAIL: 'Email address',
    PASSWORD: 'Password',
    SIGN_IN: 'Sign in',
    CURRENCY_PAGE_HEADER: 'Cryptocurrency Threshold Evaluator (past 24hrs)',
    APPLY_FILTER_MSG: 'Please apply filter to see the result.'
};
